name: Docker Compose CI

on: push

jobs:
  compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Build and Run Compose
        run: docker compose up --build
